Remove PR check for public fork

diff --git a/.github/workflows/pull-request-checks.yml b/.github/workflows/pull-request-checks.yml
--- a/.github/workflows/pull-request-checks.yml
+++ b/.github/workflows/pull-request-checks.yml
@@ -17,31 +17,31 @@ env:
     CI_LABEL: "ci:approve-public-fork-ci"
 
 jobs:
-    check-run-approval:
-        permissions:
-            pull-requests: write
-            contents: read
-        # to prevent CI from running against public forks without us looking at the code, we will check for the presence of the proper label
-        runs-on: ubuntu-latest
-        steps:
-            -   name: "If the event is to synchronize, we should remove the label from the PR"
-                # also triggers on reopen to avoid a user closing, pushing changes and then reopening the PR
-                if: ${{ github.event_name == 'pull_request_target' && (github.event.action == 'synchronize' || github.event.action == 'reopened') && github.event.pull_request.head.repo.full_name != github.repository && contains(github.event.pull_request.labels.*.name, env.CI_LABEL) }}
-                run: |
-                    echo "Synchronizing PR, removing '${{ env.CI_LABEL }}' label"
-                    gh pr edit ${{ github.event.pull_request.number }} --remove-label ${{ env.CI_LABEL }} --repo ${{ github.repository }}
-                    msg="All pull request updates require re-approval of CI.  No CI will be run."
-                    echo "::error::$msg"
-                    exit 1
-                env:
-                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-            -   name: "Check that forks have the '${{ env.CI_LABEL }}' label"
-                if: ${{ github.event.pull_request.head.repo.full_name != github.repository && !contains(github.event.pull_request.labels.*.name, env.CI_LABEL) }}
-                run: |
-                    msg="Pull request is from a public fork but does not have the '${{ env.CI_LABEL }}' label.  No CI will be run."
-                    echo "::error::$msg"
-                    exit 1
+#    check-run-approval:
+#        permissions:
+#            pull-requests: write
+#            contents: read
+#        # to prevent CI from running against public forks without us looking at the code, we will check for the presence of the proper label
+#        runs-on: ubuntu-latest
+#        steps:
+#            -   name: "If the event is to synchronize, we should remove the label from the PR"
+#                # also triggers on reopen to avoid a user closing, pushing changes and then reopening the PR
+#                if: ${{ github.event_name == 'pull_request_target' && (github.event.action == 'synchronize' || github.event.action == 'reopened') && github.event.pull_request.head.repo.full_name != github.repository && contains(github.event.pull_request.labels.*.name, env.CI_LABEL) }}
+#                run: |
+#                    echo "Synchronizing PR, removing '${{ env.CI_LABEL }}' label"
+#                    gh pr edit ${{ github.event.pull_request.number }} --remove-label ${{ env.CI_LABEL }} --repo ${{ github.repository }}
+#                    msg="All pull request updates require re-approval of CI.  No CI will be run."
+#                    echo "::error::$msg"
+#                    exit 1
+#                env:
+#                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#
+#            -   name: "Check that forks have the '${{ env.CI_LABEL }}' label"
+#                if: ${{ github.event.pull_request.head.repo.full_name != github.repository && !contains(github.event.pull_request.labels.*.name, env.CI_LABEL) }}
+#                run: |
+#                    msg="Pull request is from a public fork but does not have the '${{ env.CI_LABEL }}' label.  No CI will be run."
+#                    echo "::error::$msg"
+#                    exit 1
 
     affected-packages:
         permissions:
