add step names, remove bad code

diff --git a/.github/workflows/pull-request-checks.yml b/.github/workflows/pull-request-checks.yml
--- a/.github/workflows/pull-request-checks.yml
+++ b/.github/workflows/pull-request-checks.yml
@@ -33,24 +33,24 @@ jobs:
         # to prevent CI from running against public forks without us looking at the code, we will check for the presence of the proper label
         runs-on: ubuntu-latest
         steps:
-            -   name: "If the event is to synchronize, we should remove the label from the PR"
-                # also triggers on reopen to avoid a user closing, pushing changes and then reopening the PR
-                if: ${{ github.event_name == 'pull_request_target' && (github.event.action == 'synchronize' || github.event.action == 'reopened') && github.event.pull_request.head.repo.full_name != github.repository && contains(github.event.pull_request.labels.*.name, env.CI_LABEL) }}
-                run: |
-                    echo "Synchronizing PR, removing '${{ env.CI_LABEL }}' label"
-                    gh pr edit ${{ github.event.pull_request.number }} --remove-label ${{ env.CI_LABEL }} --repo ${{ github.repository }}
-                    msg="All pull request updates require re-approval of CI.  No CI will be run."
-                    echo "::error::$msg"
-                    exit 1
-                env:
-                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            - name: "If the event is to synchronize, we should remove the label from the PR"
+              # also triggers on reopen to avoid a user closing, pushing changes and then reopening the PR
+              if: ${{ github.event_name == 'pull_request_target' && (github.event.action == 'synchronize' || github.event.action == 'reopened') && github.event.pull_request.head.repo.full_name != github.repository && contains(github.event.pull_request.labels.*.name, env.CI_LABEL) }}
+              run: |
+                  echo "Synchronizing PR, removing '${{ env.CI_LABEL }}' label"
+                  gh pr edit ${{ github.event.pull_request.number }} --remove-label ${{ env.CI_LABEL }} --repo ${{ github.repository }}
+                  msg="All pull request updates require re-approval of CI.  No CI will be run."
+                  echo "::error::$msg"
+                  exit 1
+              env:
+                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-            -   name: "Check that forks have the '${{ env.CI_LABEL }}' label"
-                if: ${{ github.event.pull_request.head.repo.full_name != github.repository && !contains(github.event.pull_request.labels.*.name, env.CI_LABEL) }}
-                run: |
-                    msg="Pull request is from a public fork but does not have the '${{ env.CI_LABEL }}' label.  No CI will be run."
-                    echo "::error::$msg"
-                    exit 1
+            - name: "Check that forks have the '${{ env.CI_LABEL }}' label"
+              if: ${{ github.event.pull_request.head.repo.full_name != github.repository && !contains(github.event.pull_request.labels.*.name, env.CI_LABEL) }}
+              run: |
+                  msg="Pull request is from a public fork but does not have the '${{ env.CI_LABEL }}' label.  No CI will be run."
+                  echo "::error::$msg"
+                  exit 1
 
     affected-packages:
         permissions:
@@ -63,30 +63,39 @@ jobs:
             unit-tests: ${{ steps.unit-tests.outputs.changes }}
             integration-tests: ${{ steps.integration-tests.outputs.changes }}
         steps:
-        -   uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # actions/checkout@v4
-            with:
-                ref: ${{ github.event.pull_request.head.sha }}
-                repository: ${{ github.event.pull_request.head.repo.full_name }}
-        -   id: changelog-entry-check
-            uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # dorny/paths-filter@v3
-            with:
-                token: ${{ secrets.GITHUB_TOKEN }}
-                filters: .github/filters/changelog-entry-check.yml
-        -   id: verify-build
-            uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # dorny/paths-filter@v3
-            with:
-                token: ${{ secrets.GITHUB_TOKEN }}
-                filters: .github/filters/verify-build.yml
-        -   id: unit-tests
-            uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # dorny/paths-filter@v3
-            with:
-                token: ${{ secrets.GITHUB_TOKEN }}
-                filters: .github/filters/unit-tests.yml
-        -   id: integration-tests
-            uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # dorny/paths-filter@v3
-            with:
-                token: ${{ secrets.GITHUB_TOKEN }}
-                filters: .github/filters/integration-tests.yml
+            - name: "Checkout PR branch"
+              uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # actions/checkout@v4
+              with:
+                  ref: ${{ github.event.pull_request.head.sha }}
+                  repository: ${{ github.event.pull_request.head.repo.full_name }}
+
+            - name: "Check changelog entry paths"
+              id: changelog-entry-check
+              uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # dorny/paths-filter@v3
+              with:
+                  token: ${{ secrets.GITHUB_TOKEN }}
+                  filters: .github/filters/changelog-entry-check.yml
+
+            - name: "Check verify-build paths"
+              id: verify-build
+              uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # dorny/paths-filter@v3
+              with:
+                  token: ${{ secrets.GITHUB_TOKEN }}
+                  filters: .github/filters/verify-build.yml
+
+            - name: "Check unit-tests paths"
+              id: unit-tests
+              uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # dorny/paths-filter@v3
+              with:
+                  token: ${{ secrets.GITHUB_TOKEN }}
+                  filters: .github/filters/unit-tests.yml
+
+            - name: "Check integration-tests paths"
+              id: integration-tests
+              uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # dorny/paths-filter@v3
+              with:
+                  token: ${{ secrets.GITHUB_TOKEN }}
+                  filters: .github/filters/integration-tests.yml
 
     changelog-entry-check:
         uses: ./.github/workflows/_changelog-entry-check.yml
@@ -167,12 +176,20 @@ jobs:
     results:
         permissions:
             actions: read
-        name: "Pull request checks"  # keep this name, branch protection references it
+        name: "Pull request checks" # keep this name, branch protection references it
         if: ${{ !cancelled() }}
-        needs: [check-run-approval, changelog-entry-check, code-quality, verify-build, unit-tests, integration-tests]
+        needs:
+            [
+                check-run-approval,
+                changelog-entry-check,
+                code-quality,
+                verify-build,
+                unit-tests,
+                integration-tests,
+            ]
         runs-on: ${{ vars.DEFAULT_RUNNER }}
         steps:
-        -   uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # re-actors/alls-green@release/v1
-            with:
-                jobs: ${{ toJSON(needs) }}
-                allowed-skips: "changelog-entry-check,verify-build,unit-tests,integration-tests"
+            - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # re-actors/alls-green@release/v1
+              with:
+                  jobs: ${{ toJSON(needs) }}
+                  allowed-skips: "changelog-entry-check,verify-build,unit-tests,integration-tests"
